---
title: "Proyecto Final"
subtitle: "Clustering de proteínas ortólogas"
author: "Mateo Jiménez-Sotelo y Pablo Salazar-Méndez"
date: "2024-06-27"
format:
  pdf:
    pdf-engine: xelatex
    include-in-header:
      text: |
        \usepackage{fvextra}
        \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}

bibliography: ./docs/referencias.bib
csl: ./docs/apa.csl
---

# Introducción

La **minería de datos** es la disciplina por la cual la extracción de conocimiento útil a partir de grandes conjuntos de datos se hace posible. Ya que permite identificar patrones, relaciones y tendencias en los mismos, lo que a su vez facilita la generación de hipótesis y la toma de decisiones informadas en la investigación científica (@singh-2024).

Dicho campo se fundamenta en dos principales modalidades de análisis: la **clasificación** y el **clustering** o agrupamiento. Este último sigue un enfoque no supervisado, lo que significa que no requiere etiquetas o categorías predefinidas (@singh-2024). En cambio, el clustering se basa en la similitud o distancia entre los objetos de estudio para agruparlos en función de sus características compartidas (@yao-2026).

Ahora bien, el clustering **no es un proceso trivial**, ya que la naturaleza de los datos y la elección de las métricas de similitud o distancia, a.k.a. los parámetros, pueden influir significativamente en los resultados obtenidos independientemente del algoritmo elegido (@yao-2026). Por lo tanto, es crucial seleccionar cuidadosamente las técnicas de clustering y las métricas adecuadas para cada conjunto de datos específico.

En muchos de los casos, la cantidad de grupos que deben formarse no es conocida de antemano, lo que añade un nivel adicional de complejidad al proceso de clustering (@singh-2024). En este sentido, meras evaluaciones numéricas por métodos automáticos pueden no ser suficientes para determinar el número óptimo de clusters, y es posible que se requiera un análisis más profundo y una interpretación cuidadosa de los resultados para tomar decisiones informadas sobre la cantidad de grupos a formar (@singh-2024).

En suma, el clustering es una herramienta poderosa para descubrir patrones y relaciones en sistemas de interés con base en los datos, pero su aplicación requiere la selección adecuada de técnicas, métricas, y, sobretodo, un conocimiento profundo del dominio del que provienen para evitar caer en artefactos o interpretaciones erróneas de los resultados obtenidos.

# Análisis

## Obtención de datos

Para obtener las 100 secuencias homólogas se seleccionó la proteína [recA](https://www.uniprot.org/uniprotkb?query=RecA&facets=reviewed%3Atrue%2Clength%3A%5B201+TO+400%5D%2Cexistence%3A3) desde _UniProt_, puesto que contaba con un amplio repertorio de proteínas homólogas anotadas y bajo los siguientes criterios:

1. Taxonomy name: `Bacteria`
2. Status: `Reviewed (Swiss-Prot)`
3. Protein Existence: `Homology`
4. Sequence length: `201-400 AA`

La búsqueda arrojó 1,210 resultados, los cuales fueron agrupados según su taxonomía para tomar:

- 1 secuencia del grupo _Fusobacteriati_ (1 disponible)
- 14 secuencias del grupo _Thermotogati_ (14 disponibles)
- 35 secuencias del grupo _Bacillati_ (473 disponibles)
- 50 secuencias del grupo _Pseudomonadati_ (722 disponibles)

El número de secuencias elegidas de cada grupo es arbitrario y se decidió de acuerdo a qué tan abundante eran las secuencias, de menos a más.

Una vez descargadas las secuencias FASTA, se llevó a cabo el siguiente procedimiento para poder obtener la matriz de similitud y distancia entre las secuencias:

```{shell Formateando FASTA}
#| echo: true
#| eval: true
#| message: false

cut -f1 -d' ' ./data/recA_homologues.faa | awk '
/^>/ {gsub(/sp\|[A-Z0-9]+\|/, "", $0)}
{ print }
' > ./data/recA_new_headers.faa
```
```{shell Ejecución de BLASTp}
#| echo: true
#| eval: false
#| message: false

makeblastdb -in ./data/recA_new_headers.faa -dbtype prot -out ./data/recA_db

nohup bash -lc '
  blastp \
    -query ./data/recA_new_headers.faa \
    -db ./data/recA_db \
    -outfmt "6 qseqid sseqid bitscore" \
    -max_hsps 1 \
    -use_sw_tback \
    -num_threads 8 \
    > ./results/all_vs_all_bitscore.tsv
' > ./logs/all_vs_all_blastp.log 2>&1 &
```
```{shell Obteniendo la triangular superior}
#| eval: true
#| echo: true
#| message: false

# Quedarnos con N(N-1)/2 hits únicos (triangular superior)
awk -v FS="\t" -v OFS="\t" '
FNR==NR {
  if ($0 ~ /^>/) { gsub(/^>/,"",$0); ids[++n]=$0 }
  next
}
# Parseo del archivo de bitscores
# Nos quedamos con el bitscore más elevado para cada par de secuencias
{
  a=$1; b=$2; s=$3
  if (a==b) next
  if (a>b) {t=a;a=b;b=t}
  key=a SUBSEP b
  if (!(key in best) || s>best[key]) best[key]=s
}
END{
  print "qseqid","sseqid","bitscore"
  for (i=1;i<=n;i++) for (j=i+1;j<=n;j++) {
    a=ids[i]; b=ids[j]
    key=a SUBSEP b
    print a,b,(key in best ? best[key] : 0)
  }
}
' ./data/recA_new_headers.faa ./results/all_vs_all_bitscore.tsv \
> ./results/suptrian_bitscore.tsv
```

```{python Obteniendo matrices simétrica y de distancias}
#| eval: true
#| echo: true
#| message: false

from numpy import fill_diagonal
import pandas as pd

# Cargando los datos
all_vs_all = pd.read_csv("./results/suptrian_bitscore.tsv", sep="\t", header=0)

# Normalizando los bitscores
bitscore = all_vs_all["bitscore"]
all_vs_all["bitscore"] = bitscore / bitscore.max()

# Generación de la triangular superior
matrix = all_vs_all.pivot(
  index="qseqid",
  columns="sseqid",
  values="bitscore"
)

# IDs únicos en orden adecuado de las comparaciones
ids = pd.unique(
  pd.concat([all_vs_all["qseqid"], all_vs_all["sseqid"]])
)
matrix = matrix.reindex(index=ids, columns=ids)

# Reflejando valores
similarity = matrix.combine_first(matrix.T).fillna(0)
fill_diagonal(similarity.values, 1) # Similitud máxima consigo misma
distance = 1 - similarity

# Guardado
similarity.to_csv("./results/symmetric_bitscore_matrix.tsv", sep="\t")
distance.to_csv("./results/distance_matrix.tsv", sep="\t")

del similarity, distance, matrix, all_vs_all, bitscore, ids
```

## Clustering

# Resultados

# Referencias